name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  COMMITS_MESSAGES: ${{ join(github.event.commits.*.message, ',') }}

webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(env.COMMITS_MESSAGES, '#skip') }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
      - name: Build successfull
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            username: GitHub
            color: 'green'
            avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
            description: to https://ci-cd-mcz5.onrender.com by micpob
            details: ''
            footer: 'Severity: informational'
            text: A new version of Pokedex deployed
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build failed
          uses: rjstone/discord-webhook-notify@v1
          if: failure()
          with:
              severity: error
              username: GitHub
              color: 'red'
              avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
              description: commit ${{ github.head_ref }}.${{ github.sha }} by micpob broke the build
              details: ''
              footer: 'Severity: error'
              text: Build failed
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}    
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:    
      - uses: actions/checkout@v4    
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(env.COMMITS_MESSAGES, '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch